version: '3.7'
services:
  postgres:
    env_file: .env
    container_name: pro-test-postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - postgres:/data/postgres
    ports:
      - '${DB_PORT}:5432'
    networks:
      - postgres
    restart: unless-stopped
  redis:
    env_file: .env
    image: redis:latest
    environment:
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_USER=${REDIS_USER:-default}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    container_name: pro-test-redis
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - redis
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
volumes:
  postgres: