export const districts = [
    {
        id: 1,
        name_uz: 'Amudaryo tumani',
        name_ru: 'Амударский район',
        name_en: 'Amudarya district',
        region_id: 1,
    },
    {
        id: 2,
        name_uz: 'Beruniy tumani',
        name_ru: 'район Беруни',
        name_en: 'Beruni district',
        region_id: 1,
    },
    {
        id: 3,
        name_uz: 'Kegayli tumani',
        name_ru: 'Кегеиловый район',
        name_en: 'Kegeyli district',
        region_id: 1,
    },
    {
        id: 4,
        name_uz: 'Qonliko‘l tumani',
        name_ru: 'Канликул район',
        name_en: 'Kanlikul district',
        region_id: 1,
    },
    {
        id: 5,
        name_uz: 'Qorao‘zak tumani',
        name_ru: 'Блэкзакский район',
        name_en: 'Blackozak district',
        region_id: 1,
    },
    {
        id: 6,
        name_uz: 'Qo‘ng‘irot tumani',
        name_ru: 'КУНГРИАНСКИЙ район',
        name_en: 'Kungrad district',
        region_id: 1,
    },
    {
        id: 7,
        name_uz: 'Mo‘ynoq tumani',
        name_ru: 'Мойнакский район',
        name_en: 'Moynak district',
        region_id: 1,
    },
    {
        id: 8,
        name_uz: 'Nukus tumani',
        name_ru: 'Nukus район',
        name_en: 'Nukus district',
        region_id: 1,
    },
    {
        id: 9,
        name_uz: 'Nukus shahri',
        name_ru: 'Нукус город',
        name_en: 'Nukus city',
        region_id: 1,
    },
    {
        id: 10,
        name_uz: 'Taxtako‘pir tumani',
        name_ru: 'Текаконский район',
        name_en: 'Tekakon district',
        region_id: 1,
    },
    {
        id: 11,
        name_uz: 'To‘rtko‘l tumani',
        name_ru: 'Турткул район',
        name_en: 'Turtkul district',
        region_id: 1,
    },
    {
        id: 12,
        name_uz: 'Xo‘jayli tumani',
        name_ru: 'Ходжайли район',
        name_en: 'Khojayli district',
        region_id: 1,
    },
    {
        id: 13,
        name_uz: 'Chimboy tumani',
        name_ru: 'Чимбайский район',
        name_en: 'Chimbay district',
        region_id: 1,
    },
    {
        id: 14,
        name_uz: 'Shumanay tumani',
        name_ru: 'Шейманайский район',
        name_en: 'Shaymanay district',
        region_id: 1,
    },
    {
        id: 15,
        name_uz: 'Ellikqal‘a tumani',
        name_ru: 'Элликкала район',
        name_en: 'Ellikkala district',
        region_id: 1,
    },
    {
        id: 16,
        name_uz: 'Andijon shahri',
        name_ru: 'Андиджан город',
        name_en: 'Andijan city',
        region_id: 2,
    },
    {
        id: 17,
        name_uz: 'Andijon tumani',
        name_ru: 'Андиджанский район',
        name_en: 'Andijan district',
        region_id: 2,
    },
    {
        id: 18,
        name_uz: 'Asaka tumani',
        name_ru: 'Асака район',
        name_en: 'Asaka district',
        region_id: 2,
    },
    {
        id: 19,
        name_uz: 'Baliqchi tumani',
        name_ru: 'Баликчи район',
        name_en: 'Balikchi district',
        region_id: 2,
    },
    {
        id: 20,
        name_uz: 'Buloqboshi tumani',
        name_ru: 'Булакбаши район ',
        name_en: 'Bulakbashi district',
        region_id: 2,
    },
    {
        id: 21,
        name_uz: 'Bo‘z tumani',
        name_ru: 'Буз район',
        name_en: 'Bo‘z district',
        region_id: 2,
    },
    {
        id: 22,
        name_uz: 'Jalaquduq tumani',
        name_ru: 'Джалулуд район',
        name_en: 'Jalulud district',
        region_id: 2,
    },
    {
        id: 23,
        name_uz: 'Izbosgan tumani',
        name_ru: 'Избасканский район',
        name_en: 'Izbaskan district',
        region_id: 2,
    },
    {
        id: 24,
        name_uz: 'Qorasuv shahri',
        name_ru: 'Корасув район',
        name_en: 'Kharasuv сшен',
        region_id: 2,
    },
    {
        id: 25,
        name_uz: 'Qo‘rg‘ontepa tumani',
        name_ru: 'Кургантета район',
        name_en: 'Kurganteta district',
        region_id: 2,
    },
    {
        id: 26,
        name_uz: 'Marhamat tumani',
        name_ru: 'Мархамат район',
        name_en: 'Marhamat district',
        region_id: 2,
    },
    {
        id: 27,
        name_uz: 'Oltinko‘l tumani',
        name_ru: 'АЛТИНКУЛЬСКИЙ район',
        name_en: 'Altynkul district',
        region_id: 2,
    },
    {
        id: 28,
        name_uz: 'Paxtaobod tumani',
        name_ru: 'Пахтаабадский район',
        name_en: 'Pakhtaabad district',
        region_id: 2,
    },
    {
        id: 29,
        name_uz: 'Ulug‘nor tumani',
        name_ru: 'Ульгинский район',
        name_en: 'Ulugny district',
        region_id: 2,
    },
    {
        id: 30,
        name_uz: 'Xonabod tumani',
        name_ru: 'Ханабадский район',
        name_en: 'Khanabad district',
        region_id: 2,
    },
    {
        id: 31,
        name_uz: 'Xo‘jaobod tumani',
        name_ru: 'Ходжабадский район',
        name_en: 'Khojaabad district',
        region_id: 2,
    },
    {
        id: 32,
        name_uz: 'Shahrixon tumani',
        name_ru: 'Шахриханский район',
        name_en: 'Shahrihan district',
        region_id: 2,
    },
    {
        id: 33,
        name_uz: 'Buxoro shahri',
        name_ru: 'Бухара город',
        name_en: 'Bukhara city',
        region_id: 3,
    },
    {
        id: 34,
        name_uz: 'Buxoro tumani',
        name_ru: 'Бухара район',
        name_en: 'Bukhara district',
        region_id: 3,
    },
    {
        id: 35,
        name_uz: 'Vobkent tumani',
        name_ru: 'ВОБКАНТ район',
        name_en: 'Vobkent district',
        region_id: 3,
    },
    {
        id: 36,
        name_uz: 'G‘ijduvon tumani',
        name_ru: 'ГИДЖДУВАНСКИЙ район',
        name_en: 'Gijduvan district',
        region_id: 3,
    },
    {
        id: 37,
        name_uz: 'Jondor tumani',
        name_ru: 'Жандар район',
        name_en: 'Jondor district',
        region_id: 3,
    },
    {
        id: 38,
        name_uz: 'Kogon tumani',
        name_ru: 'Каганский район',
        name_en: 'Kagan district',
        region_id: 3,
    },
    {
        id: 39,
        name_uz: 'Kogon shahri',
        name_ru: 'Когон город',
        name_en: 'Kogon city',
        region_id: 3,
    },
    {
        id: 40,
        name_uz: 'Qorako‘l tumani',
        name_ru: 'Каракул район',
        name_en: 'Karakul district',
        region_id: 3,
    },
    {
        id: 41,
        name_uz: 'Qorovulbozor tumani',
        name_ru: 'Каравулбозорский район',
        name_en: 'Karavulbozor district',
        region_id: 3,
    },
    {
        id: 42,
        name_uz: 'Olot tumani',
        name_ru: 'Алат район',
        name_en: 'Alat district',
        region_id: 3,
    },
    {
        id: 43,
        name_uz: 'Peshku tumani',
        name_ru: 'Пешку район',
        name_en: 'Peshku district',
        region_id: 3,
    },
    {
        id: 44,
        name_uz: 'Romitan tumani',
        name_ru: 'Ромитанский район',
        name_en: 'Romitan district',
        region_id: 3,
    },
    {
        id: 45,
        name_uz: 'Shofirkon tumani',
        name_ru: 'Шафирканский район',
        name_en: 'Shafirkan district',
        region_id: 3,
    },
    {
        id: 46,
        name_uz: 'Arnasoy tumani',
        name_ru: 'Арнасейский район',
        name_en: 'Arnasay district',
        region_id: 4,
    },
    {
        id: 47,
        name_uz: 'Baxmal tumani',
        name_ru: 'Бахмальный район',
        name_en: 'Bakhmal district',
        region_id: 4,
    },
    {
        id: 48,
        name_uz: 'G‘allaorol tumani',
        name_ru: 'Галлаорул район',
        name_en: 'Gallaorol district',
        region_id: 4,
    },
    {
        id: 49,
        name_uz: 'Do‘stlik tumani',
        name_ru: 'Дустлик район',
        name_en: 'Dustlik district',
        region_id: 4,
    },
    {
        id: 50,
        name_uz: 'Sh.Rashidov tumani',
        name_ru: 'Ш.Рашидовский район',
        name_en: 'Sh.Rashidov district',
        region_id: 4,
    },
    {
        id: 51,
        name_uz: 'Jizzax shahri',
        name_ru: 'Джизак город',
        name_en: 'Jizzakh city',
        region_id: 4,
    },
    {
        id: 52,
        name_uz: 'Zarbdor tumani',
        name_ru: 'Зарбдор район',
        name_en: 'Zarbdor district',
        region_id: 4,
    },
    {
        id: 53,
        name_uz: 'Zafarobod tumani',
        name_ru: 'Зафарабадский район',
        name_en: 'Zafarabad district',
        region_id: 4,
    },
    {
        id: 54,
        name_uz: 'Zomin tumani',
        name_ru: 'Зааминский район',
        name_en: 'Zaamin district',
        region_id: 4,
    },
    {
        id: 55,
        name_uz: 'Mirzacho‘l tumani',
        name_ru: 'Мирзачул район',
        name_en: 'Mirzachul district',
        region_id: 4,
    },
    {
        id: 56,
        name_uz: 'Paxtakor tumani',
        name_ru: 'Пахтакор район',
        name_en: 'Pakhtakor district',
        region_id: 4,
    },
    {
        id: 57,
        name_uz: 'Forish tumani',
        name_ru: 'Фопиш округ',
        name_en: 'Forish district',
        region_id: 4,
    },
    {
        id: 58,
        name_uz: 'Yangiobod tumani',
        name_ru: 'Янгиабадский район',
        name_en: 'Yangiabad district',
        region_id: 4,
    },
    {
        id: 59,
        name_uz: 'G‘uzor tumani',
        name_ru: 'Гузарский район',
        name_en: 'Guzar district',
        region_id: 5,
    },
    {
        id: 60,
        name_uz: 'Dehqonobod tumani',
        name_ru: 'Дехканабадский район',
        name_en: 'Dehkanabad district',
        region_id: 5,
    },
    {
        id: 61,
        name_uz: 'Qamashi tumani',
        name_ru: 'Камбаши район',
        name_en: 'Kambashi district',
        region_id: 5,
    },
    {
        id: 62,
        name_uz: 'Qarshi tumani',
        name_ru: 'Карши район',
        name_en: 'Karshi district',
        region_id: 5,
    },
    {
        id: 63,
        name_uz: 'Qarshi shahri',
        name_ru: 'Карши город',
        name_en: 'Karshi city',
        region_id: 5,
    },
    {
        id: 64,
        name_uz: 'Kasbi tumani',
        name_ru: 'Касби район',
        name_en: 'Kasbi district',
        region_id: 5,
    },
    {
        id: 65,
        name_uz: 'Kitob tumani',
        name_ru: 'Китоб район',
        name_en: 'Kitab district',
        region_id: 5,
    },
    {
        id: 66,
        name_uz: 'Koson tumani',
        name_ru: 'Касанский район',
        name_en: 'Kasan district',
        region_id: 5,
    },
    {
        id: 67,
        name_uz: 'Mirishkor tumani',
        name_ru: 'Миришкор район',
        name_en: 'Mirishkor district',
        region_id: 5,
    },
    {
        id: 68,
        name_uz: 'Muborak tumani',
        name_ru: 'Мубарак район',
        name_en: 'Mubarak district',
        region_id: 5,
    },
    {
        id: 69,
        name_uz: 'Nishon tumani',
        name_ru: 'Нишон район',
        name_en: 'Nishon district',
        region_id: 5,
    },
    {
        id: 70,
        name_uz: 'Chiroqchi tumani',
        name_ru: 'Чиракчи район',
        name_en: 'Chirakchi district',
        region_id: 5,
    },
    {
        id: 71,
        name_uz: 'Shahrisabz tumani',
        name_ru: 'Шахрисабц район',
        name_en: 'Shahrisabz district district',
        region_id: 5,
    },
    {
        id: 72,
        name_uz: 'Yakkabog‘ tumani',
        name_ru: 'Яккабогский район',
        name_en: 'Yakkabog district',
        region_id: 5,
    },
    {
        id: 73,
        name_uz: 'Zarafshon shahri',
        name_ru: 'Зарафшан город',
        name_en: 'Zarafshan city',
        region_id: 6,
    },
    {
        id: 74,
        name_uz: 'Karmana tumani',
        name_ru: 'Кармана район',
        name_en: 'Karmana district',
        region_id: 6,
    },
    {
        id: 75,
        name_uz: 'Qiziltepa tumani',
        name_ru: 'Кизилтепа район',
        name_en: 'Kyzyltepa district',
        region_id: 6,
    },
    {
        id: 76,
        name_uz: 'Konimex tumani',
        name_ru: 'Konimex район',
        name_en: 'Konimex district',
        region_id: 6,
    },
    {
        id: 77,
        name_uz: 'Navbahor tumani',
        name_ru: 'Навбахорский район',
        name_en: 'Navbahor district',
        region_id: 6,
    },
    {
        id: 78,
        name_uz: 'Navoiy shahri',
        name_ru: 'Навоий город',
        name_en: 'Navoi city',
        region_id: 6,
    },
    {
        id: 79,
        name_uz: 'Nurota tumani',
        name_ru: 'Нурта район',
        name_en: 'Nurata district',
        region_id: 6,
    },
    {
        id: 80,
        name_uz: 'Tomdi tumani',
        name_ru: 'Томди район',
        name_en: 'Tomdi district',
        region_id: 6,
    },
    {
        id: 81,
        name_uz: 'Uchquduq tumani',
        name_ru: 'Учкудук район',
        name_en: 'Uchkuduk district',
        region_id: 6,
    },
    {
        id: 82,
        name_uz: 'Xatirchi tumani',
        name_ru: 'Крайрчи район',
        name_en: 'Khatirchi district',
        region_id: 6,
    },
    {
        id: 83,
        name_uz: 'Kosonsoy tumani',
        name_ru: 'Козонсойский район',
        name_en: 'Kosonsoy district',
        region_id: 7,
    },
    {
        id: 84,
        name_uz: 'Mingbuloq tumani',
        name_ru: 'Минбулак район',
        name_en: 'Mingbulak district',
        region_id: 7,
    },
    {
        id: 85,
        name_uz: 'Namangan tumani',
        name_ru: 'Наманганский район',
        name_en: 'Namangan district',
        region_id: 7,
    },
    {
        id: 86,
        name_uz: 'Namangan shahri',
        name_ru: 'Наманган город',
        name_en: 'Namangan city',
        region_id: 7,
    },
    {
        id: 87,
        name_uz: 'Norin tumani',
        name_ru: 'Норин район',
        name_en: 'Тфкшт district',
        region_id: 7,
    },
    {
        id: 88,
        name_uz: 'Pop tumani',
        name_ru: 'Поп район',
        name_en: 'Pop district',
        region_id: 7,
    },
    {
        id: 89,
        name_uz: 'To‘raqo‘rg‘on tumani',
        name_ru: 'Туракурганский район',
        name_en: 'Turakurgan district',
        region_id: 7,
    },
    {
        id: 90,
        name_uz: 'Uychi tumani',
        name_ru: 'Уйчи район',
        name_en: 'Uychi district',
        region_id: 7,
    },
    {
        id: 91,
        name_uz: 'Uchqo‘rg‘on tumani',
        name_ru: 'Учкурганский район',
        name_en: 'Uchkurgan district',
        region_id: 7,
    },
    {
        id: 92,
        name_uz: 'Chortoq tumani',
        name_ru: 'Чортак район',
        name_en: 'Chartak district',
        region_id: 7,
    },
    {
        id: 93,
        name_uz: 'Chust tumani',
        name_ru: 'Чуст район',
        name_en: 'Chust district',
        region_id: 7,
    },
    {
        id: 94,
        name_uz: 'Yangiqo‘rg‘on tumani',
        name_ru: 'Янгикурганский район',
        name_en: 'Yangikurgan district',
        region_id: 7,
    },
    {
        id: 95,
        name_uz: 'Bulung‘ur tumani',
        name_ru: 'БУЛУНГУРНЫЙ район',
        name_en: 'Bulungur district',
        region_id: 8,
    },
    {
        id: 96,
        name_uz: 'Jomboy tumani',
        name_ru: 'Джамбайский район',
        name_en: 'Jambay district',
        region_id: 8,
    },
    {
        id: 97,
        name_uz: 'Ishtixon tumani',
        name_ru: 'Иштихонский район',
        name_en: 'Ishtikhon district',
        region_id: 8,
    },
    {
        id: 98,
        name_uz: 'Kattaqo‘rg‘on tumani',
        name_ru: 'Каттакрганский район',
        name_en: 'Kattakurgan district',
        region_id: 8,
    },
    {
        id: 99,
        name_uz: 'Kattaqo‘rg‘on shahri',
        name_ru: 'Каттакурган город',
        name_en: 'Kattakurgan city',
        region_id: 8,
    },
    {
        id: 100,
        name_uz: 'Qo‘shrabot tumani',
        name_ru: 'Кошрабат район',
        name_en: 'Koshrabat district',
        region_id: 8,
    },
    {
        id: 101,
        name_uz: 'Narpay tumani',
        name_ru: 'Нарпайский район',
        name_en: 'Narpay district',
        region_id: 8,
    },
    {
        id: 102,
        name_uz: 'Nurabod tumani',
        name_ru: 'Нурабод район ',
        name_en: 'Nurabod district',
        region_id: 8,
    },
    {
        id: 103,
        name_uz: 'Oqdaryo tumani',
        name_ru: 'Акдаря район',
        name_en: 'Akdarya district',
        region_id: 8,
    },
    {
        id: 104,
        name_uz: 'Payariq tumani',
        name_ru: 'Пайарик район ',
        name_en: 'Payarik district',
        region_id: 8,
    },
    {
        id: 105,
        name_uz: 'Pastarg‘om tumani',
        name_ru: 'Пастдаргамский район',
        name_en: 'Pastarkom district',
        region_id: 8,
    },
    {
        id: 106,
        name_uz: 'Paxtachi tumani',
        name_ru: 'ПАХТАЧИ район',
        name_en: 'Pakhtachi district',
        region_id: 8,
    },
    {
        id: 107,
        name_uz: 'Samarqand tumani',
        name_ru: 'Самаркандский район',
        name_en: 'Samarkand district',
        region_id: 8,
    },
    {
        id: 108,
        name_uz: 'Samarqand shahri',
        name_ru: 'Самарканд город',
        name_en: 'Samarkand city',
        region_id: 8,
    },
    {
        id: 109,
        name_uz: 'Toyloq tumani',
        name_ru: 'Тайлак район',
        name_en: 'Taylak district',
        region_id: 8,
    },
    {
        id: 110,
        name_uz: 'Urgut tumani',
        name_ru: 'Ургутский район',
        name_en: 'Urgut district',
        region_id: 8,
    },
    {
        id: 111,
        name_uz: 'Angor tumani',
        name_ru: 'Ангорский район',
        name_en: 'Angor district',
        region_id: 9,
    },
    {
        id: 112,
        name_uz: 'Boysun tumani',
        name_ru: 'Бойсун район',
        name_en: 'Boysun district',
        region_id: 9,
    },
    {
        id: 113,
        name_uz: 'Denov tumani',
        name_ru: 'Денов район',
        name_en: 'Denau district',
        region_id: 9,
    },
    {
        id: 114,
        name_uz: 'Jarqo‘rg‘on tumani',
        name_ru: 'Джаркурганский район',
        name_en: 'Jarkurgan district',
        region_id: 9,
    },
    {
        id: 115,
        name_uz: 'Qiziriq tumani',
        name_ru: 'Кизирик район',
        name_en: 'Qiziriq district',
        region_id: 9,
    },
    {
        id: 116,
        name_uz: 'Qo‘mqo‘rg‘on tumani',
        name_ru: 'Кумкурганский район',
        name_en: 'Kumkurgan district',
        region_id: 9,
    },
    {
        id: 117,
        name_uz: 'Muzrabot tumani',
        name_ru: 'Музработ район',
        name_en: 'Muzrabot district',
        region_id: 9,
    },
    {
        id: 118,
        name_uz: 'Oltinsoy tumani',
        name_ru: 'Олтинсейский район',
        name_en: 'Oltinsay district',
        region_id: 9,
    },
    {
        id: 119,
        name_uz: 'Sariosiyo tumani',
        name_ru: 'Сариосио район',
        name_en: 'Sariosiyo district',
        region_id: 9,
    },
    {
        id: 120,
        name_uz: 'Termiz tumani',
        name_ru: 'Термиз район',
        name_en: 'Termez district',
        region_id: 9,
    },
    {
        id: 121,
        name_uz: 'Termiz shahri',
        name_ru: 'Термин город',
        name_en: 'Termez city',
        region_id: 9,
    },
    {
        id: 122,
        name_uz: 'Uzun tumani',
        name_ru: 'Узун район',
        name_en: 'Uzun district',
        region_id: 9,
    },
    {
        id: 123,
        name_uz: 'Sherobod tumani',
        name_ru: 'Шерабадский район',
        name_en: 'Sherabad district',
        region_id: 9,
    },
    {
        id: 124,
        name_uz: 'Sho‘rchi tumani',
        name_ru: 'Шурчи район',
        name_en: 'Shurchi district',
        region_id: 9,
    },
    {
        id: 125,
        name_uz: 'Boyovut tumani',
        name_ru: 'Бойовут район ',
        name_en: 'Boyovut district',
        region_id: 10,
    },
    {
        id: 126,
        name_uz: 'Guliston tumani',
        name_ru: 'Гулистана район ',
        name_en: 'Gulistan district',
        region_id: 10,
    },
    {
        id: 127,
        name_uz: 'Guliston shahri',
        name_ru: 'Гулистан город',
        name_en: 'Gulistan city',
        region_id: 10,
    },
    {
        id: 128,
        name_uz: 'Mirzaobod tumani',
        name_ru: 'Мирзаабадский район',
        name_en: 'Mirzaabad district',
        region_id: 10,
    },
    {
        id: 129,
        name_uz: 'Oqoltin tumani',
        name_ru: 'Акальтинский район',
        name_en: 'Akaltin district',
        region_id: 10,
    },
    {
        id: 130,
        name_uz: 'Sayxunobod tumani',
        name_ru: 'Сайхунабад район ',
        name_en: 'Sayhunabad district',
        region_id: 10,
    },
    {
        id: 131,
        name_uz: 'Sardoba tumani',
        name_ru: 'Сардоба район',
        name_en: 'Sardoba district',
        region_id: 10,
    },
    {
        id: 132,
        name_uz: 'Sirdaryo tumani',
        name_ru: 'СИРДАРЕЙСКИЙ район',
        name_en: 'Syrdarya district',
        region_id: 10,
    },
    {
        id: 133,
        name_uz: 'Xavos tumani',
        name_ru: 'Хавос район',
        name_en: 'Havos district',
        region_id: 10,
    },
    {
        id: 134,
        name_uz: 'Shirin shahri',
        name_ru: 'Ширин город',
        name_en: 'Shirin city',
        region_id: 10,
    },
    {
        id: 135,
        name_uz: 'Yangiyer shahri',
        name_ru: 'Янгийер город',
        name_en: 'Yangiyer city',
        region_id: 10,
    },
    {
        id: 136,
        name_uz: 'Angiren shahri',
        name_ru: 'АНГИРЕН город',
        name_en: 'Angiren city',
        region_id: 11,
    },
    {
        id: 137,
        name_uz: 'Bekabod tumani',
        name_ru: 'Бекабадский район',
        name_en: 'Bekabad district',
        region_id: 11,
    },
    {
        id: 138,
        name_uz: 'Bekabod shahri',
        name_ru: 'Бекабод город',
        name_en: 'Bekabod city',
        region_id: 11,
    },
    {
        id: 139,
        name_uz: 'Bo‘ka tumani',
        name_ru: 'Бока район',
        name_en: 'Boka district',
        region_id: 11,
    },
    {
        id: 140,
        name_uz: 'Bo‘stonliq tumani',
        name_ru: 'Бостанликский район',
        name_en: 'Bostanlyk district',
        region_id: 11,
    },
    {
        id: 141,
        name_uz: 'Zangiota tumani',
        name_ru: 'Зангиота район',
        name_en: 'Zangiota district',
        region_id: 11,
    },
    {
        id: 142,
        name_uz: 'Qibray tumani',
        name_ru: 'Кибрай район ',
        name_en: 'Qibray district',
        region_id: 11,
    },
    {
        id: 143,
        name_uz: 'Quyichirchiq tumani',
        name_ru: 'Куйи Чирчик район',
        name_en: 'Quyichirchik district',
        region_id: 11,
    },
    {
        id: 144,
        name_uz: 'Oqqo‘rg‘on tumani',
        name_ru: 'Аккурганский район',
        name_en: 'Akkurgan district',
        region_id: 11,
    },
    {
        id: 145,
        name_uz: 'Olmaliq shahri',
        name_ru: 'Алмалмк город',
        name_en: 'Almalik city',
        region_id: 11,
    },
    {
        id: 146,
        name_uz: 'Ohangaron tumani',
        name_ru: 'Ахангарон район',
        name_en: 'Ahangaron district',
        region_id: 11,
    },
    {
        id: 147,
        name_uz: 'Parkent tumani',
        name_ru: 'Паркенский район',
        name_en: 'Parkent district',
        region_id: 11,
    },
    {
        id: 148,
        name_uz: 'Piskent tumani',
        name_ru: 'Пискент район',
        name_en: 'Piskent district',
        region_id: 11,
    },
    {
        id: 149,
        name_uz: 'O‘rtachirchiq tumani',
        name_ru: 'Урта Чирчик район',
        name_en: 'Ortachirchik district',
        region_id: 11,
    },
    {
        id: 150,
        name_uz: 'Chinoz tumani',
        name_ru: 'Чиноз район',
        name_en: 'Chinoz district',
        region_id: 11,
    },
    {
        id: 151,
        name_uz: 'Chirchiq shahri',
        name_ru: 'Чирчик город',
        name_en: 'Chirchik city',
        region_id: 11,
    },
    {
        id: 152,
        name_uz: 'Yuqorichirchiq tumani',
        name_ru: 'Юкори Чирхик район',
        name_en: 'Yukorichirchik district',
        region_id: 11,
    },
    {
        id: 153,
        name_uz: 'Yangiyo‘l tumani',
        name_ru: 'Янги йул район',
        name_en: 'Yangiyul district',
        region_id: 11,
    },
    {
        id: 154,
        name_uz: 'Beshariq tumani',
        name_ru: 'Бешарик район',
        name_en: 'Besharik district',
        region_id: 12,
    },
    {
        id: 155,
        name_uz: 'Bog‘dod tumani',
        name_ru: 'Багдадский район',
        name_en: 'Baghdad district',
        region_id: 12,
    },
    {
        id: 156,
        name_uz: 'Buvayda tumani',
        name_ru: 'Бувайда район ',
        name_en: 'Buvay district',
        region_id: 12,
    },
    {
        id: 157,
        name_uz: 'Dang‘ara tumani',
        name_ru: 'Дангара район ',
        name_en: 'Dangara district',
        region_id: 12,
    },
    {
        id: 158,
        name_uz: 'Yozyovon tumani',
        name_ru: 'Ёзёвон район',
        name_en: 'Yozyovon district',
        region_id: 12,
    },
    {
        id: 159,
        name_uz: 'Quva tumani',
        name_ru: 'Қува район',
        name_en: 'Quva district',
        region_id: 12,
    },
    {
        id: 160,
        name_uz: 'Quvasoy shahri',
        name_ru: 'Қувасой район',
        name_en: 'Quvvasoy city',
        region_id: 12,
    },
    {
        id: 161,
        name_uz: 'Qo‘qon shahri',
        name_ru: 'Коканд город',
        name_en: 'Kokand city',
        region_id: 12,
    },
    {
        id: 162,
        name_uz: 'Qo‘shtepa tumani',
        name_ru: 'Коштепа район',
        name_en: 'Koshtepa district',
        region_id: 12,
    },
    {
        id: 163,
        name_uz: 'Marg‘ilon shahri',
        name_ru: 'Маргилан город',
        name_en: 'Margilan city',
        region_id: 12,
    },
    {
        id: 164,
        name_uz: 'Oltiariq tumani',
        name_ru: 'Альтиарик район',
        name_en: 'Altiariq district',
        region_id: 12,
    },
    {
        id: 165,
        name_uz: 'Rishton tumani',
        name_ru: 'Риштана район ',
        name_en: 'Rishtan district',
        region_id: 12,
    },
    {
        id: 166,
        name_uz: 'So‘x tumani',
        name_ru: 'Сох район',
        name_en: 'Sokh district',
        region_id: 12,
    },
    {
        id: 167,
        name_uz: 'Toshloq tumani',
        name_ru: 'Тошлок район',
        name_en: 'Toshloq district',
        region_id: 12,
    },
    {
        id: 168,
        name_uz: 'Uchko‘prik tumani',
        name_ru: 'Учкоприк район',
        name_en: 'Uchkoprik district',
        region_id: 12,
    },
    {
        id: 169,
        name_uz: 'O‘zbekiston tumani',
        name_ru: 'Узбекистан район',
        name_en: 'Uzbekistan district',
        region_id: 12,
    },
    {
        id: 170,
        name_uz: 'Farg‘ona tumani',
        name_ru: 'Фергана район ',
        name_en: 'Fergana district',
        region_id: 12,
    },
    {
        id: 171,
        name_uz: 'Farg‘ona shahri',
        name_ru: 'Ферганский город',
        name_en: 'Fergana city',
        region_id: 12,
    },
    {
        id: 172,
        name_uz: 'Furqat tumani',
        name_ru: 'Фуркат район',
        name_en: 'Furkat district',
        region_id: 12,
    },
    {
        id: 173,
        name_uz: 'Bog‘ot tumani',
        name_ru: 'Багат район ',
        name_en: 'Bagat district',
        region_id: 13,
    },
    {
        id: 174,
        name_uz: 'Gurlan tumani',
        name_ru: 'Гурлан район',
        name_en: 'Gurlan district',
        region_id: 13,
    },
    {
        id: 175,
        name_uz: 'Qo‘shko‘pir tumani',
        name_ru: 'Кошкопирский район',
        name_en: 'Koshkopir district',
        region_id: 13,
    },
    {
        id: 176,
        name_uz: 'Urganch tumani',
        name_ru: 'Ургенский район',
        name_en: 'Urgench district',
        region_id: 13,
    },
    {
        id: 177,
        name_uz: 'Urganch shahri',
        name_ru: 'Ургенч город',
        name_en: 'Urgench city',
        region_id: 13,
    },
    {
        id: 178,
        name_uz: 'Xiva tumani',
        name_ru: 'Хива район',
        name_en: 'Khiva district',
        region_id: 13,
    },
    {
        id: 179,
        name_uz: 'Xazarasp tumani',
        name_ru: 'Хазарасп район',
        name_en: 'Khazarasp district',
        region_id: 13,
    },
    {
        id: 180,
        name_uz: 'Xonqa tumani',
        name_ru: 'Хонка район',
        name_en: 'Khonqa district',
        region_id: 13,
    },
    {
        id: 181,
        name_uz: 'Shavot tumani',
        name_ru: 'Шавот район',
        name_en: 'Shavat district',
        region_id: 13,
    },
    {
        id: 182,
        name_uz: 'Yangiariq tumani',
        name_ru: 'Янгиарийский район',
        name_en: 'Yangiariq district',
        region_id: 13,
    },
    {
        id: 183,
        name_uz: 'Yangibozor tumani',
        name_ru: 'Янгибазарский район',
        name_en: 'Yangibazar district',
        region_id: 13,
    },
    {
        id: 184,
        name_uz: 'Bektimer tumani',
        name_ru: 'БЕКТИМЕРСКИЙ район',
        name_en: 'Bekthimer district',
        region_id: 14,
    },
    {
        id: 185,
        name_uz: "Mirzo Ulug'bek tumani",
        name_ru: 'Мирзо Улугбек район',
        name_en: 'Mirzo Ulugbek district',
        region_id: 14,
    },
    {
        id: 186,
        name_uz: 'Mirobod tumani',
        name_ru: 'Мирабад район ',
        name_en: 'Mirabad district',
        region_id: 14,
    },
    {
        id: 187,
        name_uz: 'Olmazor tumani',
        name_ru: 'Альмазарский район',
        name_en: 'Almazar district',
        region_id: 14,
    },
    {
        id: 188,
        name_uz: "Sirg'ali tumani",
        name_ru: 'Сергели район',
        name_en: 'Sergeli district',
        region_id: 14,
    },
    {
        id: 189,
        name_uz: 'Uchtepa tumani',
        name_ru: 'Учтепа район',
        name_en: 'Uchtepa district',
        region_id: 14,
    },
    {
        id: 190,
        name_uz: 'Yashnobod tumani',
        name_ru: 'Яшнабадский район',
        name_en: 'Yashnabad district',
        region_id: 14,
    },
    {
        id: 191,
        name_uz: 'Chilonzor tumani',
        name_ru: 'Чиланзарский район',
        name_en: 'Chilanzar district',
        region_id: 14,
    },
    {
        id: 192,
        name_uz: 'Shayxontohur tumani',
        name_ru: 'Шайхантахурский район',
        name_en: 'Shayhantahur district',
        region_id: 14,
    },
    {
        id: 193,
        name_uz: 'Yunusobod tumani',
        name_ru: 'Юнусабадский район',
        name_en: 'Yunusabad district',
        region_id: 14,
    },
    {
        id: 194,
        name_uz: 'Yakkasaroy tumani',
        name_ru: 'Яккасарайский район',
        name_en: 'Yakkasaray district',
        region_id: 14,
    },
    {
        id: 195,
        name_uz: 'Taxiatosh shahri',
        name_ru: 'Тахиташ город',
        name_en: 'Takhiatash city',
        region_id: 1,
    },
    {
        id: 196,
        name_uz: 'Asaka shahri',
        name_ru: 'Асака город',
        name_en: 'Asaka city',
        region_id: 2,
    },
    {
        id: 197,
        name_uz: 'Bandixon tumani',
        name_ru: 'Бандикссон район',
        name_en: 'BANDIXON district',
        region_id: 9,
    },
    {
        id: 198,
        name_uz: 'Ohangaron shahri',
        name_ru: 'Ахангарон город',
        name_en: 'Ahangaron city',
        region_id: 11,
    },
    {
        id: 199,
        name_uz: 'Yangiyo‘l shahri',
        name_ru: 'Янгиюл город',
        name_en: 'Yangiyul city',
        region_id: 11,
    },
    {
        id: 200,
        name_uz: 'Toshkent tumani',
        name_ru: 'Ташкент район',
        name_en: 'Tashkent district',
        region_id: 11,
    },
    {
        id: 201,
        name_uz: 'Xiva shahri',
        name_ru: 'Хива город',
        name_en: 'Khiva city',
        region_id: 13,
    },
    {
        id: 202,
        name_uz: "Do'stlik shahri",
        name_ru: 'Дўстлик город',
        name_en: "Do'stlik city",
        region_id: 13,
    },
    {
        id: 203,
        name_uz: 'Yangihayot tumani',
        name_ru: 'Янгиҳаёт район',
        name_en: 'Yanghayimat district',
        region_id: 14,
    },
    {
        id: 204,
        name_uz: 'Tuproqqala tumani',
        name_ru: 'ТИЛКАТЛА район',
        name_en: 'Tilqatla district',
        region_id: 13,
    },
    {
        id: 205,
        name_uz: 'Davlatobod tumani',
        name_ru: 'Давлатабад район ',
        name_en: 'Davlatabad district',
        region_id: 7,
    },
    {
        id: 206,
        name_uz: 'G‘ozg‘on shahri',
        name_ru: 'Ғозғон город',
        name_en: 'Gazonga city',
        region_id: 6,
    },
    {
        id: 207,
        name_uz: 'Bo‘zatov tumani',
        name_ru: 'Бўзатов район',
        name_en: 'Burzazov district',
        region_id: 1,
    },
    {
        id: 208,
        name_uz: 'Shahrisabz shahri',
        name_ru: 'ШАХРИСАБЗ город',
        name_en: 'Shahrisabz city',
        region_id: 5,
    },
    {
        id: 209,
        name_uz: "Ko'kdala tumani",
        name_ru: 'Кўкдала район',
        name_en: 'Kokdala district',
        region_id: 5,
    },
    {
        id: 210,
        name_uz: 'Izboskan tumani',
        name_ru: 'ИзБоскан район',
        name_en: 'Izbaskan district',
        region_id: 2,
    },
    {
        id: 211,
        name_uz: 'Xonobod shahar',
        name_ru: 'Хонобод город',
        name_en: 'Khonobod city',
        region_id: 2,
    },
    {
        id: 212,
        name_uz: 'Bo‘ston tumani',
        name_ru: 'Бустон район',
        name_en: 'Buston district',
        region_id: 2,
    },
    {
        id: 213,
        name_uz: 'Bag‘dod tumani',
        name_ru: 'Багдод район',
        name_en: 'Bagdad district',
        region_id: 12,
    },
    {
        id: 214,
        name_uz: 'Sharof Rashidov tumani',
        name_ru: 'Шароф Рашидов район',
        name_en: 'Sharof Rashidov district',
        region_id: 4,
    },
    {
        id: 215,
        name_uz: 'Uchqo’rg’on tumani',
        name_ru: 'Учкурган район',
        name_en: 'Uchkurgan district',
        region_id: 7,
    },
    {
        id: 216,
        name_uz: 'Yangiqo’rg’on tumani',
        name_ru: 'Янгикурган район',
        name_en: 'Yangikurgan district',
        region_id: 7,
    },
    {
        id: 217,
        name_uz: 'To’raqo’rg’on tumani',
        name_ru: 'Тўроқўрғон район',
        name_en: 'Turaqurgan district',
        region_id: 7,
    },
    {
        id: 218,
        name_uz: 'Uchqo’rg’on tumani',
        name_ru: 'Учкурган район',
        name_en: 'Uchkurgan district',
        region_id: 7,
    },
    {
        id: 219,
        name_uz: 'Yangi Namangan tumani',
        name_ru: 'Янги Наманган район',
        name_en: 'Yangi Namangan district',
        region_id: 7,
    },
    {
        id: 220,
        name_uz: 'Yakkabog’ tumani',
        name_ru: 'Яккабог район',
        name_en: 'Yakkabog district',
        region_id: 5,
    },
    {
        id: 221,
        name_uz: 'G’uzor tumani',
        name_ru: 'Гузор район',
        name_en: "G'uzor district",
        region_id: 5,
    },
    {
        id: 222,
        name_uz: 'Qanliko‘l tumani',
        name_ru: 'Канлыкўл район',
        name_en: 'Kanlikol district',
        region_id: 1,
    },
    {
        id: 223,
        name_uz: 'Kegeyli tumani',
        name_ru: 'Кегейли район',
        name_en: 'Kegeyli district',
        region_id: 1,
    },
    {
        id: 224,
        name_uz: 'Ellikqala tumani',
        name_ru: 'Элликқала район',
        name_en: 'Ellikqala district',
        region_id: 1,
    },
    {
        id: 225,
        name_uz: 'Buzatov tumani',
        name_ru: 'Бузатов район',
        name_en: 'Buzatov district',
        region_id: 1,
    },
    {
        id: 226,
        name_uz: 'Bulung’ur tumani',
        name_ru: 'Булунғур район',
        name_en: 'Bulungur district',
        region_id: 9,
    },
    {
        id: 227,
        name_uz: 'Nurobod tumani',
        name_ru: 'Нуробод район',
        name_en: 'Nurabad district',
        region_id: 9,
    },
    {
        id: 228,
        name_uz: "Bo'ston tumani",
        name_ru: 'Бустон район',
        name_en: 'Buston district',
        region_id: 2,
    },
    {
        id: 229,
        name_uz: 'Kattaqo’rg’on shahri',
        name_ru: 'Каттақўрғон город',
        name_en: "Kattaqo'rg'on city",
        region_id: 8,
    },
    {
        id: 230,
        name_uz: 'Pastdarg‘om tumani',
        name_ru: 'Пастдарғом район',
        name_en: 'Pastdargom district',
        region_id: 8,
    },
    {
        id: 231,
        name_uz: 'Xovos tumani',
        name_ru: 'Ховос район',
        name_en: 'Khovos district',
        region_id: 10,
    },
    {
        id: 232,
        name_uz: 'Bandihon tumani',
        name_ru: 'Бандихон район',
        name_en: 'Bandikhon district',
        region_id: 9,
    },
    {
        id: 233,
        name_uz: 'Qumqo‘rg‘on tumani',
        name_ru: 'Қумқўрғон район',
        name_en: 'Kumkurgan district',
        region_id: 9,
    },
    {
        id: 234,
        name_uz: 'Shayxontoxur tumani',
        name_ru: 'Шайхантахур район',
        name_en: 'Shaykhantakhur district',
        region_id: 14,
    },
    {
        id: 235,
        name_uz: 'Sirg’ali tumani',
        name_ru: 'Сирғали район',
        name_en: 'Sirgali district',
        region_id: 14,
    },
    {
        id: 236,
        name_uz: 'Bektemir tumani',
        name_ru: 'Бектемир район',
        name_en: 'Bektemir district',
        region_id: 14,
    },
    {
        id: 237,
        name_uz: 'Bekobod tumani',
        name_ru: 'Бекобод район',
        name_en: 'Bekabad district',
        region_id: 11,
    },
    {
        id: 238,
        name_uz: 'Nurafshon tumani',
        name_ru: 'Нурафшон район',
        name_en: 'Nurafshon district',
        region_id: 11,
    },
    {
        id: 239,
        name_uz: 'Angren tumani',
        name_ru: 'Ангрен район',
        name_en: 'Angren district',
        region_id: 11,
    },
    {
        id: 240,
        name_uz: 'Shovot tumani',
        name_ru: 'Шовот район',
        name_en: 'Shavat district',
        region_id: 13,
    },
    {
        id: 241,
        name_uz: 'Xazorasp tumani',
        name_ru: 'Хазорасп район',
        name_en: 'Khazorasp district',
        region_id: 13,
    },
    {
        id: 242,
        name_uz: "Yangiyo'l tumani",
        name_ru: 'Янгиёл район',
        name_en: 'Yangiyul district',
        region_id: 11,
    },
    {
        id: 243,
        name_uz: 'Oxongaron tumani',
        name_ru: 'Охунгарон район',
        name_en: 'Okhangaron district',
        region_id: 11,
    },
    {
        id: 244,
        name_uz: 'Ellikqal’a tumani',
        name_ru: 'Элликқалъа район',
        name_en: 'Ellikqala district',
        region_id: 1,
    },
    {
        id: 245,
        name_uz: 'Juma shahar',
        name_ru: 'Джума город',
        name_en: 'Juma city',
        region_id: 8,
    },
    {
        id: 246,
        name_uz: 'Dexonobod tumani',
        name_ru: 'Дехқонобод район',
        name_en: 'Dekhkanabad district',
        region_id: 5,
    },
    {
        id: 247,
        name_uz: 'Ulug‘bek tumani',
        name_ru: 'Улугбек район',
        name_en: 'Ulugbek district',
        region_id: 14,
    },
    {
        id: 248,
        name_uz: 'Hazorasp tumani',
        name_ru: 'Хазорасп район',
        name_en: 'Khazorasp district',
        region_id: 13,
    },
    {
        id: 249,
        name_uz: 'Sergeli tumani',
        name_ru: 'Сергели район',
        name_en: 'Sergeli district',
        region_id: 14,
    },
    {
        id: 250,
        name_uz: 'Toshkent shahar',
        name_ru: 'Ташкент город',
        name_en: 'Tashkent city',
        region_id: 14,
    },
    {
        id: 251,
        name_uz: 'Chirchik tumani',
        name_ru: 'Чирчик район',
        name_en: 'Chirchik district',
        region_id: 11,
    },
    {
        id: 252,
        name_uz: 'Sharg‘un shahri',
        name_ru: 'Шарғун город',
        name_en: 'Shargun city',
        region_id: 9,
    },
    {
        id: 253,
        name_uz: 'Paxtachi tumani',
        name_ru: 'Пахтачи район',
        name_en: 'Pakhtachi district',
        region_id: 8,
    },
    {
        id: 254,
        name_uz: 'Toshkent shahri',
        name_ru: 'Ташкент город',
        name_en: 'Tashkent city',
        region_id: 14,
    },
    {
        id: 255,
        name_uz: 'Kibray tumani',
        name_ru: 'Кибрай район',
        name_en: 'Kibray district',
        region_id: 11,
    },
    {
        id: 256,
        name_uz: 'Yangiyul tuman',
        name_ru: 'Янгиюль район',
        name_en: 'Yangiyul district',
        region_id: 11,
    },
    {
        id: 257,
        name_uz: 'Tuproqqal’a tumani',
        name_ru: 'Тупроққалъа район',
        name_en: 'Tuprokkala district',
        region_id: 13,
    },
    {
        id: 258,
        name_uz: 'Shaxrisabz tumani',
        name_ru: 'Шахрисабз район',
        name_en: 'Shakhrisabz district',
        region_id: 5,
    },
    {
        id: 259,
        name_uz: 'Shayhontoxur tuman',
        name_ru: 'Шайхантахур район',
        name_en: 'Shaykhantakhur district',
        region_id: 14,
    },
];
