export const baseRegions = [
    {
        id: 1,
        name_uz: 'Qoraqalpog‘iston Respublikasi',
        name_ru: 'Республика Каракалпакстан',
        name_en: 'Republic of Karakalpakstan',
    },
    {
        id: 2,
        name_uz: 'Andijon viloyati',
        name_ru: 'Андижанская область',
        name_en: 'Andijan region',
    },
    {
        id: 3,
        name_uz: 'Buxoro viloyati',
        name_ru: 'Бухарская область',
        name_en: 'Bukhara region',
    },
    {
        id: 4,
        name_uz: 'Jizzax viloyati',
        name_ru: 'Джизакская область',
        name_en: 'Jizzakh region',
    },
    {
        id: 5,
        name_uz: 'Qashqadaryo viloyati',
        name_ru: 'Кашкадарьинская область',
        name_en: 'Kashkadarya region',
    },
    {
        id: 6,
        name_uz: 'Navoiy viloyati',
        name_ru: 'Навоийская область',
        name_en: 'Navoi region',
    },
    {
        id: 7,
        name_uz: 'Namangan viloyati',
        name_ru: 'Наманганская область',
        name_en: 'Namangan region',
    },
    {
        id: 8,
        name_uz: 'Samarqand viloyati',
        name_ru: 'Самаркандская область',
        name_en: 'Samarkand region',
    },
    {
        id: 9,
        name_uz: 'Surxandaryo viloyati',
        name_ru: 'Сурхандарьинская область',
        name_en: 'Surkhandarya region',
    },
    {
        id: 10,
        name_uz: 'Sirdaryo viloyati',
        name_ru: 'Сырдарьинская область',
        name_en: 'Syrdarya region',
    },
    {
        id: 11,
        name_uz: 'Toshkent viloyati',
        name_ru: 'Ташкентская область',
        name_en: 'Tashkent region',
    },
    {
        id: 12,
        name_uz: 'Farg‘ona viloyati',
        name_ru: 'Ферганская область',
        name_en: 'Fergana region',
    },
    {
        id: 13,
        name_uz: 'Xorazm viloyati',
        name_ru: 'Хорезмская область',
        name_en: 'Khorezm region',
    },
    {
        id: 14,
        name_uz: 'Toshkent shahri',
        name_ru: 'Город Ташкент',
        name_en: 'Tashkent city',
    },
    {
        id: 15,
        name_uz: 'Boshqa',
        name_ru: 'Другой',
        name_en: 'Other',
    },
];
